import { environmentGLSL } from "./environment";
export const fullscreenVertex = `void main(){gl_Position=vec4(position,1.);}`;
export const proceduralFragment = `precision highp float;uniform vec2 uResolution,uPointer;uniform float uTime,uIor,uBrightness,uContrast,uRainbow;${environmentGLSL}
mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);} vec3 turn(vec3 p){p.xz*=rot(uPointer.x);p.yz*=rot(uPointer.y);return p;}
float gem(vec3 q){vec3 p=turn(q);float a=atan(p.z,p.x),sector=3.14159265/8.;float f=floor((a+sector*.5)/sector)*sector;float radial=dot(p.xz,vec2(cos(f),sin(f)));float crown=max(radial+.72*p.y-.83,p.y-.38);float pavilion=max(radial-1.18*p.y-.89,-p.y-.95);float girdle=radial-.91;return max(girdle,max(crown,pavilion));}
vec3 normalAt(vec3 p){vec2 e=vec2(.002,0);return normalize(vec3(gem(p+e.xyy)-gem(p-e.xyy),gem(p+e.yxy)-gem(p-e.yxy),gem(p+e.yyx)-gem(p-e.yyx)));}
float march(vec3 ro,vec3 rd,out vec3 p){float t=0.;for(int i=0;i<54;i++){p=ro+rd*t;float d=gem(p);if(abs(d)<.0015||t>8.)break;t+=max(d*.7,.008);}return t;}
vec3 traceChannel(vec3 rd,vec3 p,vec3 n,float eta){vec3 inside=refract(rd,n,1./eta);vec3 q=p+inside*.015;for(int i=0;i<34;i++){float d=-gem(q);if(d<.001){vec3 ni=-normalAt(q);vec3 outRay=refract(inside,ni,eta);if(length(outRay)>.1)return environment(outRay);inside=reflect(inside,ni);q+=inside*.012;}q+=inside*max(d*.52,.007);}return environment(reflect(rd,n));}
void main(){vec2 uv=(gl_FragCoord.xy*2.-uResolution)/uResolution.y;vec3 ro=vec3(0,.12,3.35),rd=normalize(vec3(uv,-2.35)),p;float t=march(ro,rd,p);vec3 bg=environment(rd)*(.5+.3*pow(1.-abs(uv.y),3.));if(t>8.){gl_FragColor=vec4(pow(bg,vec3(.4545)),1.);return;}vec3 n=normalAt(p);float d=uRainbow*.045;vec3 col;col.r=traceChannel(rd,p,n,uIor-d).r;col.g=traceChannel(rd,p,n,uIor).g;col.b=traceChannel(rd,p,n,uIor+d).b;float F=pow((uIor-1.)/(uIor+1.),2.);F=F+(1.-F)*pow(1.-max(dot(-rd,n),0.),5.);col=mix(col,environment(reflect(rd,n))*1.8,F);col=(col-.5)*uContrast+.5;col*=uBrightness;col=col/(1.+col);gl_FragColor=vec4(pow(max(col,0.),vec3(.4545)),1.);}`;
